server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myweb1?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: password

  redis:
    database: 0
    timeout: 1000
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:



mybatis:

  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wanting.me.entity

  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.wanting.me.mapper: debug
upload:
  temp: C:\workspace57\MyWebFont\resources\upload\
  knowledge:
    img: images\knowledge\
  user:
    img: images\user\
