server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myweb1?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: password


mybatis:

  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wanting.me.entity

  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.wanting.me.mapper: debug
upload:
  temp: C:\workspace57\MyWebFont\resources\upload\
  knowledge:
    img: images\knowledge\
  user:
    img: images\user\
